//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics;

namespace VotRite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        public static string[] encryptCols = {"field_name", "field_value", "field_title", "race_loc_title", "loc_voted_position", "party_logo", "party_name", "tenant_name", "apartment",
    "name", "slate_logo", "cand_name",  "cand_photo", "party_logo", "prop_loc_name", "prop_loc_text","county",
    "new_prop_loc_text", "positive_answer", "negative_answer",  "contest_generic_name", "top_heading", "election_name", "location",
    "shares_factor", "board", "overview_file", "pass", "email", "current_license_key", "client_name", "license_key", "MachineNo",
    "Location", "BackupDrive", "MainLocation" };
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("")]
        public string secretCipherKey
        {
            get
            {
                return (string)this[nameof(secretCipherKey)];
            }
            set
            {
                this[nameof(secretCipherKey)] = (object)value;
            }
        }

    }
}
