using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using VotRiteBallotDataManager.AppCode;

namespace VotRite.Forms
{
    public class IdentifyTenantForm2 : Form
    {
        private DataGridViewTextBoxColumn Apartment;
        private DataGridViewTextBoxColumn TenantName;
        private Button btnCancel;
        private Button btnSelect;
        private Button btn_VK_0;
        private Button btn_VK_1;
        private Button btn_VK_2;
        private Button btn_VK_3;
        private Button btn_VK_4;
        private Button btn_VK_5;
        private Button btn_VK_6;
        private Button btn_VK_7;
        private Button btn_VK_8;
        private Button btn_VK_9;
        private Button btn_VK_A;
        private Button btn_VK_B;
        private Button btn_VK_BACKSPACE;
        private Button btn_VK_C;
        private Button btn_VK_D;
        private Button btn_VK_E;
        private Button btn_VK_F;
        private Button btn_VK_G;
        private Button btn_VK_H;
        private Button btn_VK_I;
        private Button btn_VK_J;
        private Button btn_VK_K;
        private Button btn_VK_L;
        private Button btn_VK_M;
        private Button btn_VK_N;
        private Button btn_VK_O;
        private Button btn_VK_P;
        private Button btn_VK_Q;
        private Button btn_VK_R;
        private Button btn_VK_S;
        private Button btn_VK_SPACE;
        private Button btn_VK_T;
        private Button btn_VK_U;
        private Button btn_VK_V;
        private Button btn_VK_W;
        private Button btn_VK_X;
        private Button btn_VK_Y;
        private Button btn_VK_Z;
        private DataGridView dgvTenants;
        private Label lblFilter;
        private TableLayoutPanel pnlButtons;
        private TableLayoutPanel pnlDataGrid;
        private TableLayoutPanel pnlFilter;
        private Panel pnlKeyboardContainer;
        private TableLayoutPanel tblButtonsContainer;
        private TextBox txtFilter;

        public IdentifyTenantForm2()
        {
            InitializeComponent();
            dgvTenants.AutoGenerateColumns = false;
        }

        public Tenant SelectedTenant { get; set; }
        private DataTable tableSource { get; set; }
        private List<Tenant> Tenants { get; set; }

        private void btn_VK_Click(object sender, EventArgs e)
        {
            SetFocusToInput();
            var button = sender as Button;
            switch (button.Name)
            {
                case "btn_VK_SPACE":
                    SendKeys.Send(" ");
                    return;

                case "btn_VK_BACKSPACE":
                    SendKeys.Send("{BS}");
                    return;
            }
            SendKeys.Send(button.Name.Substring(7).ToUpper());
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            DialogResult = DialogResult.Cancel;
            Close();
        }

        private void btnSelect_Click(object sender, EventArgs e)
        {
            if (dgvTenants.SelectedRows.Count != 0)
            {
                int index =
                    tableSource.Rows.IndexOf((dgvTenants.SelectedRows[0].DataBoundItem as DataRowView).Row);
                SelectedTenant = Tenants.ElementAt(index);
                DialogResult = DialogResult.OK;
                Close();
            }
        }

        private void dgvTenants_SelectionChanged(object sender, EventArgs e)
        {
            SetFocusToInput();
            btnSelect.Enabled = dgvTenants.SelectedRows.Count > 0;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        private void IdentifyTenantForm2_FormClosed(object sender, FormClosedEventArgs e)
        {
        }

        private void IdentifyTenantForm2_Load(object sender, EventArgs e)
        {
            Tenants = Tenant.GetAllTenants(AppManager.BallotId);
            tableSource = ToDataTable(Tenants);
            SetFocusToInput();
        }

        private void InitializeComponent()
        {
            var style = new DataGridViewCellStyle();
            var style2 = new DataGridViewCellStyle();
            var style3 = new DataGridViewCellStyle();
            var style4 = new DataGridViewCellStyle();
            pnlButtons = new TableLayoutPanel();
            btnSelect = new Button();
            btnCancel = new Button();
            dgvTenants = new DataGridView();
            pnlDataGrid = new TableLayoutPanel();
            pnlFilter = new TableLayoutPanel();
            lblFilter = new Label();
            txtFilter = new TextBox();
            pnlKeyboardContainer = new Panel();
            tblButtonsContainer = new TableLayoutPanel();
            btn_VK_BACKSPACE = new Button();
            btn_VK_SPACE = new Button();
            btn_VK_Z = new Button();
            btn_VK_Y = new Button();
            btn_VK_X = new Button();
            btn_VK_W = new Button();
            btn_VK_V = new Button();
            btn_VK_U = new Button();
            btn_VK_T = new Button();
            btn_VK_S = new Button();
            btn_VK_R = new Button();
            btn_VK_Q = new Button();
            btn_VK_P = new Button();
            btn_VK_O = new Button();
            btn_VK_N = new Button();
            btn_VK_M = new Button();
            btn_VK_L = new Button();
            btn_VK_K = new Button();
            btn_VK_J = new Button();
            btn_VK_I = new Button();
            btn_VK_H = new Button();
            btn_VK_G = new Button();
            btn_VK_F = new Button();
            btn_VK_E = new Button();
            btn_VK_D = new Button();
            btn_VK_C = new Button();
            btn_VK_B = new Button();
            btn_VK_A = new Button();
            btn_VK_0 = new Button();
            btn_VK_9 = new Button();
            btn_VK_8 = new Button();
            btn_VK_7 = new Button();
            btn_VK_6 = new Button();
            btn_VK_5 = new Button();
            btn_VK_4 = new Button();
            btn_VK_3 = new Button();
            btn_VK_2 = new Button();
            btn_VK_1 = new Button();
            Apartment = new DataGridViewTextBoxColumn();
            TenantName = new DataGridViewTextBoxColumn();
            pnlButtons.SuspendLayout();
            ((ISupportInitialize) dgvTenants).BeginInit();
            pnlDataGrid.SuspendLayout();
            pnlFilter.SuspendLayout();
            pnlKeyboardContainer.SuspendLayout();
            tblButtonsContainer.SuspendLayout();
            SuspendLayout();
            pnlButtons.ColumnCount = 2;
            pnlButtons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            pnlButtons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            pnlButtons.Controls.Add(btnSelect, 0, 0);
            pnlButtons.Controls.Add(btnCancel, 0, 0);
            pnlButtons.Dock = DockStyle.Bottom;
            pnlButtons.Location = new Point(0, 0x2af);
            pnlButtons.Name = "pnlButtons";
            pnlButtons.RowCount = 1;
            pnlButtons.RowStyles.Add(new RowStyle(SizeType.Percent, 50f));
            pnlButtons.Size = new Size(0x428, 0x74);
            pnlButtons.TabIndex = 1;
            btnSelect.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            btnSelect.Enabled = false;
            btnSelect.FlatStyle = FlatStyle.Flat;
            btnSelect.Font = new Font("Segoe UI", 32f);
            btnSelect.Location = new Point(0x2de, 0x10);
            btnSelect.Margin = new Padding(0, 0, 40, 40);
            btnSelect.MaximumSize = new Size(290, 60);
            btnSelect.MinimumSize = new Size(290, 60);
            btnSelect.Name = "btnSelect";
            btnSelect.Size = new Size(290, 60);
            btnSelect.TabIndex = 2;
            btnSelect.Text = "Select";
            btnSelect.UseVisualStyleBackColor = true;
            btnSelect.Click += btnSelect_Click;
            btnCancel.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            btnCancel.DialogResult = DialogResult.Cancel;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 32f);
            btnCancel.Location = new Point(40, 0x10);
            btnCancel.Margin = new Padding(40, 0, 0, 40);
            btnCancel.MaximumSize = new Size(290, 60);
            btnCancel.MinimumSize = new Size(290, 60);
            btnCancel.Name = "btnCancel";
            btnCancel.Size = new Size(290, 60);
            btnCancel.TabIndex = 1;
            btnCancel.Text = "Cancel";
            btnCancel.UseVisualStyleBackColor = true;
            btnCancel.Click += btnCancel_Click;
            dgvTenants.AllowUserToAddRows = false;
            dgvTenants.AllowUserToDeleteRows = false;
            dgvTenants.AllowUserToOrderColumns = true;
            dgvTenants.BackgroundColor = Color.White;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("Microsoft Sans Serif", 24f, FontStyle.Regular, GraphicsUnit.Pixel, 0xcc);
            style.ForeColor = SystemColors.WindowText;
            style.Padding = new Padding(5);
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            dgvTenants.ColumnHeadersDefaultCellStyle = style;
            dgvTenants.ColumnHeadersHeight = 50;
            dgvTenants.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvTenants.Columns.AddRange(new DataGridViewColumn[] {TenantName, Apartment});
            dgvTenants.Dock = DockStyle.Fill;
            dgvTenants.GridColor = Color.White;
            dgvTenants.Location = new Point(0x2b, 0x13);
            dgvTenants.MultiSelect = false;
            dgvTenants.Name = "dgvTenants";
            dgvTenants.ReadOnly = true;
            dgvTenants.RowHeadersVisible = false;
            style2.Font = new Font("Microsoft Sans Serif", 24f, FontStyle.Regular, GraphicsUnit.Point, 0xcc);
            style2.Padding = new Padding(5);
            dgvTenants.RowsDefaultCellStyle = style2;
            dgvTenants.RowTemplate.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dgvTenants.RowTemplate.DefaultCellStyle.Padding = new Padding(5);
            dgvTenants.RowTemplate.Height = 50;
            dgvTenants.RowTemplate.ReadOnly = true;
            dgvTenants.RowTemplate.Resizable = DataGridViewTriState.False;
            dgvTenants.ScrollBars = ScrollBars.Vertical;
            dgvTenants.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvTenants.ShowCellErrors = false;
            dgvTenants.ShowCellToolTips = false;
            dgvTenants.ShowEditingIcon = false;
            dgvTenants.ShowRowErrors = false;
            dgvTenants.Size = new Size(0x3d2, 0x152);
            dgvTenants.TabIndex = 2;
            dgvTenants.SelectionChanged += dgvTenants_SelectionChanged;
            pnlDataGrid.ColumnCount = 1;
            pnlDataGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50f));
            pnlDataGrid.Controls.Add(dgvTenants, 0, 0);
            pnlDataGrid.Dock = DockStyle.Bottom;
            pnlDataGrid.Location = new Point(0, 0x147);
            pnlDataGrid.Name = "pnlDataGrid";
            pnlDataGrid.Padding = new Padding(40, 0x10, 40, 0);
            pnlDataGrid.RowCount = 1;
            pnlDataGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 50f));
            pnlDataGrid.Size = new Size(0x428, 360);
            pnlDataGrid.TabIndex = 3;
            pnlFilter.ColumnCount = 2;
            pnlFilter.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 620f));
            pnlFilter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
            pnlFilter.Controls.Add(lblFilter, 0, 0);
            pnlFilter.Controls.Add(txtFilter, 1, 0);
            pnlFilter.Dock = DockStyle.Bottom;
            pnlFilter.Location = new Point(0, 0xfe);
            pnlFilter.Name = "pnlFilter";
            pnlFilter.Padding = new Padding(40, 0, 40, 0);
            pnlFilter.RowCount = 1;
            pnlFilter.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            pnlFilter.Size = new Size(0x428, 0x49);
            pnlFilter.TabIndex = 4;
            lblFilter.Dock = DockStyle.Bottom;
            lblFilter.Font = new Font("Segoe UI", 32f);
            lblFilter.Location = new Point(0x2b, 10);
            lblFilter.Name = "lblFilter";
            lblFilter.Size = new Size(0x266, 0x3f);
            lblFilter.TabIndex = 0;
            lblFilter.Text = "Filter by name or apartment";
            lblFilter.TextAlign = ContentAlignment.MiddleCenter;
            txtFilter.BorderStyle = BorderStyle.FixedSingle;
            txtFilter.Dock = DockStyle.Bottom;
            txtFilter.Font = new Font("Microsoft Sans Serif", 32f, FontStyle.Regular, GraphicsUnit.Point, 0xcc);
            txtFilter.Location = new Point(660, 0x11);
            txtFilter.Margin = new Padding(0);
            txtFilter.Name = "txtFilter";
            txtFilter.Size = new Size(0x16c, 0x38);
            txtFilter.TabIndex = 1;
            txtFilter.TextChanged += txtFilter_TextChanged;
            pnlKeyboardContainer.Controls.Add(tblButtonsContainer);
            pnlKeyboardContainer.Dock = DockStyle.Fill;
            pnlKeyboardContainer.Location = new Point(0, 0);
            pnlKeyboardContainer.Name = "pnlKeyboardContainer";
            pnlKeyboardContainer.Padding = new Padding(40, 40, 40, 0);
            pnlKeyboardContainer.Size = new Size(0x428, 0xfe);
            pnlKeyboardContainer.TabIndex = 5;
            tblButtonsContainer.ColumnCount = 10;
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10f));
            tblButtonsContainer.Controls.Add(btn_VK_BACKSPACE, 8, 3);
            tblButtonsContainer.Controls.Add(btn_VK_SPACE, 6, 3);
            tblButtonsContainer.Controls.Add(btn_VK_Z, 5, 3);
            tblButtonsContainer.Controls.Add(btn_VK_Y, 4, 3);
            tblButtonsContainer.Controls.Add(btn_VK_X, 3, 3);
            tblButtonsContainer.Controls.Add(btn_VK_W, 2, 3);
            tblButtonsContainer.Controls.Add(btn_VK_V, 1, 3);
            tblButtonsContainer.Controls.Add(btn_VK_U, 0, 3);
            tblButtonsContainer.Controls.Add(btn_VK_T, 9, 2);
            tblButtonsContainer.Controls.Add(btn_VK_S, 8, 2);
            tblButtonsContainer.Controls.Add(btn_VK_R, 7, 2);
            tblButtonsContainer.Controls.Add(btn_VK_Q, 6, 2);
            tblButtonsContainer.Controls.Add(btn_VK_P, 5, 2);
            tblButtonsContainer.Controls.Add(btn_VK_O, 4, 2);
            tblButtonsContainer.Controls.Add(btn_VK_N, 3, 2);
            tblButtonsContainer.Controls.Add(btn_VK_M, 2, 2);
            tblButtonsContainer.Controls.Add(btn_VK_L, 1, 2);
            tblButtonsContainer.Controls.Add(btn_VK_K, 0, 2);
            tblButtonsContainer.Controls.Add(btn_VK_J, 9, 1);
            tblButtonsContainer.Controls.Add(btn_VK_I, 8, 1);
            tblButtonsContainer.Controls.Add(btn_VK_H, 7, 1);
            tblButtonsContainer.Controls.Add(btn_VK_G, 6, 1);
            tblButtonsContainer.Controls.Add(btn_VK_F, 5, 1);
            tblButtonsContainer.Controls.Add(btn_VK_E, 4, 1);
            tblButtonsContainer.Controls.Add(btn_VK_D, 3, 1);
            tblButtonsContainer.Controls.Add(btn_VK_C, 2, 1);
            tblButtonsContainer.Controls.Add(btn_VK_B, 1, 1);
            tblButtonsContainer.Controls.Add(btn_VK_A, 0, 1);
            tblButtonsContainer.Controls.Add(btn_VK_0, 9, 0);
            tblButtonsContainer.Controls.Add(btn_VK_9, 8, 0);
            tblButtonsContainer.Controls.Add(btn_VK_8, 7, 0);
            tblButtonsContainer.Controls.Add(btn_VK_7, 6, 0);
            tblButtonsContainer.Controls.Add(btn_VK_6, 5, 0);
            tblButtonsContainer.Controls.Add(btn_VK_5, 4, 0);
            tblButtonsContainer.Controls.Add(btn_VK_4, 3, 0);
            tblButtonsContainer.Controls.Add(btn_VK_3, 2, 0);
            tblButtonsContainer.Controls.Add(btn_VK_2, 1, 0);
            tblButtonsContainer.Controls.Add(btn_VK_1, 0, 0);
            tblButtonsContainer.Dock = DockStyle.Fill;
            tblButtonsContainer.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            tblButtonsContainer.Location = new Point(40, 40);
            tblButtonsContainer.Name = "tblButtonsContainer";
            tblButtonsContainer.RowCount = 4;
            tblButtonsContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 25f));
            tblButtonsContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 25f));
            tblButtonsContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 25f));
            tblButtonsContainer.RowStyles.Add(new RowStyle(SizeType.Percent, 25f));
            tblButtonsContainer.Size = new Size(0x3d8, 0xd6);
            tblButtonsContainer.TabIndex = 1;
            tblButtonsContainer.SetColumnSpan(btn_VK_BACKSPACE, 2);
            btn_VK_BACKSPACE.Dock = DockStyle.Fill;
            btn_VK_BACKSPACE.FlatStyle = FlatStyle.Flat;
            btn_VK_BACKSPACE.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_BACKSPACE.Location = new Point(0x315, 0xa4);
            btn_VK_BACKSPACE.Margin = new Padding(5);
            btn_VK_BACKSPACE.Name = "btn_VK_BACKSPACE";
            btn_VK_BACKSPACE.Size = new Size(190, 0x2d);
            btn_VK_BACKSPACE.TabIndex = 0x2e;
            btn_VK_BACKSPACE.Text = "BACKSPACE";
            btn_VK_BACKSPACE.UseVisualStyleBackColor = true;
            btn_VK_BACKSPACE.Click += btn_VK_Click;
            tblButtonsContainer.SetColumnSpan(btn_VK_SPACE, 2);
            btn_VK_SPACE.Dock = DockStyle.Fill;
            btn_VK_SPACE.FlatStyle = FlatStyle.Flat;
            btn_VK_SPACE.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_SPACE.Location = new Point(0x251, 0xa4);
            btn_VK_SPACE.Margin = new Padding(5);
            btn_VK_SPACE.Name = "btn_VK_SPACE";
            btn_VK_SPACE.Size = new Size(0xba, 0x2d);
            btn_VK_SPACE.TabIndex = 0x29;
            btn_VK_SPACE.Text = "SPACE";
            btn_VK_SPACE.UseVisualStyleBackColor = true;
            btn_VK_SPACE.Click += btn_VK_Click;
            btn_VK_Z.Dock = DockStyle.Fill;
            btn_VK_Z.FlatStyle = FlatStyle.Flat;
            btn_VK_Z.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_Z.Location = new Point(0x1ef, 0xa4);
            btn_VK_Z.Margin = new Padding(5);
            btn_VK_Z.Name = "btn_VK_Z";
            btn_VK_Z.Size = new Size(0x58, 0x2d);
            btn_VK_Z.TabIndex = 0x23;
            btn_VK_Z.Text = "Z";
            btn_VK_Z.UseVisualStyleBackColor = true;
            btn_VK_Z.Click += btn_VK_Click;
            btn_VK_Y.Dock = DockStyle.Fill;
            btn_VK_Y.FlatStyle = FlatStyle.Flat;
            btn_VK_Y.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_Y.Location = new Point(0x18d, 0xa4);
            btn_VK_Y.Margin = new Padding(5);
            btn_VK_Y.Name = "btn_VK_Y";
            btn_VK_Y.Size = new Size(0x58, 0x2d);
            btn_VK_Y.TabIndex = 0x22;
            btn_VK_Y.Text = "Y";
            btn_VK_Y.UseVisualStyleBackColor = true;
            btn_VK_Y.Click += btn_VK_Click;
            btn_VK_X.Dock = DockStyle.Fill;
            btn_VK_X.FlatStyle = FlatStyle.Flat;
            btn_VK_X.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_X.Location = new Point(0x12b, 0xa4);
            btn_VK_X.Margin = new Padding(5);
            btn_VK_X.Name = "btn_VK_X";
            btn_VK_X.Size = new Size(0x58, 0x2d);
            btn_VK_X.TabIndex = 0x21;
            btn_VK_X.Text = "X";
            btn_VK_X.UseVisualStyleBackColor = true;
            btn_VK_X.Click += btn_VK_Click;
            btn_VK_W.Dock = DockStyle.Fill;
            btn_VK_W.FlatStyle = FlatStyle.Flat;
            btn_VK_W.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_W.Location = new Point(0xc9, 0xa4);
            btn_VK_W.Margin = new Padding(5);
            btn_VK_W.Name = "btn_VK_W";
            btn_VK_W.Size = new Size(0x58, 0x2d);
            btn_VK_W.TabIndex = 0x20;
            btn_VK_W.Text = "W";
            btn_VK_W.UseVisualStyleBackColor = true;
            btn_VK_W.Click += btn_VK_Click;
            btn_VK_V.Dock = DockStyle.Fill;
            btn_VK_V.FlatStyle = FlatStyle.Flat;
            btn_VK_V.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_V.Location = new Point(0x67, 0xa4);
            btn_VK_V.Margin = new Padding(5);
            btn_VK_V.Name = "btn_VK_V";
            btn_VK_V.Size = new Size(0x58, 0x2d);
            btn_VK_V.TabIndex = 0x1f;
            btn_VK_V.Text = "V";
            btn_VK_V.UseVisualStyleBackColor = true;
            btn_VK_V.Click += btn_VK_Click;
            btn_VK_U.Dock = DockStyle.Fill;
            btn_VK_U.FlatStyle = FlatStyle.Flat;
            btn_VK_U.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_U.Location = new Point(5, 0xa4);
            btn_VK_U.Margin = new Padding(5);
            btn_VK_U.Name = "btn_VK_U";
            btn_VK_U.Size = new Size(0x58, 0x2d);
            btn_VK_U.TabIndex = 30;
            btn_VK_U.Text = "U";
            btn_VK_U.UseVisualStyleBackColor = true;
            btn_VK_U.Click += btn_VK_Click;
            btn_VK_T.Dock = DockStyle.Fill;
            btn_VK_T.FlatStyle = FlatStyle.Flat;
            btn_VK_T.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_T.Location = new Point(0x377, 0x6f);
            btn_VK_T.Margin = new Padding(5);
            btn_VK_T.Name = "btn_VK_T";
            btn_VK_T.Size = new Size(0x5c, 0x2b);
            btn_VK_T.TabIndex = 0x1d;
            btn_VK_T.Text = "T";
            btn_VK_T.UseVisualStyleBackColor = true;
            btn_VK_T.Click += btn_VK_Click;
            btn_VK_S.Dock = DockStyle.Fill;
            btn_VK_S.FlatStyle = FlatStyle.Flat;
            btn_VK_S.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_S.Location = new Point(0x315, 0x6f);
            btn_VK_S.Margin = new Padding(5);
            btn_VK_S.Name = "btn_VK_S";
            btn_VK_S.Size = new Size(0x58, 0x2b);
            btn_VK_S.TabIndex = 0x1c;
            btn_VK_S.Text = "S";
            btn_VK_S.UseVisualStyleBackColor = true;
            btn_VK_S.Click += btn_VK_Click;
            btn_VK_R.Dock = DockStyle.Fill;
            btn_VK_R.FlatStyle = FlatStyle.Flat;
            btn_VK_R.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_R.Location = new Point(0x2b3, 0x6f);
            btn_VK_R.Margin = new Padding(5);
            btn_VK_R.Name = "btn_VK_R";
            btn_VK_R.Size = new Size(0x58, 0x2b);
            btn_VK_R.TabIndex = 0x1b;
            btn_VK_R.Text = "R";
            btn_VK_R.UseVisualStyleBackColor = true;
            btn_VK_R.Click += btn_VK_Click;
            btn_VK_Q.Dock = DockStyle.Fill;
            btn_VK_Q.FlatStyle = FlatStyle.Flat;
            btn_VK_Q.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_Q.Location = new Point(0x251, 0x6f);
            btn_VK_Q.Margin = new Padding(5);
            btn_VK_Q.Name = "btn_VK_Q";
            btn_VK_Q.Size = new Size(0x58, 0x2b);
            btn_VK_Q.TabIndex = 0x1a;
            btn_VK_Q.Text = "Q";
            btn_VK_Q.UseVisualStyleBackColor = true;
            btn_VK_Q.Click += btn_VK_Click;
            btn_VK_P.Dock = DockStyle.Fill;
            btn_VK_P.FlatStyle = FlatStyle.Flat;
            btn_VK_P.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_P.Location = new Point(0x1ef, 0x6f);
            btn_VK_P.Margin = new Padding(5);
            btn_VK_P.Name = "btn_VK_P";
            btn_VK_P.Size = new Size(0x58, 0x2b);
            btn_VK_P.TabIndex = 0x19;
            btn_VK_P.Text = "P";
            btn_VK_P.UseVisualStyleBackColor = true;
            btn_VK_P.Click += btn_VK_Click;
            btn_VK_O.Dock = DockStyle.Fill;
            btn_VK_O.FlatStyle = FlatStyle.Flat;
            btn_VK_O.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_O.Location = new Point(0x18d, 0x6f);
            btn_VK_O.Margin = new Padding(5);
            btn_VK_O.Name = "btn_VK_O";
            btn_VK_O.Size = new Size(0x58, 0x2b);
            btn_VK_O.TabIndex = 0x18;
            btn_VK_O.Text = "O";
            btn_VK_O.UseVisualStyleBackColor = true;
            btn_VK_O.Click += btn_VK_Click;
            btn_VK_N.Dock = DockStyle.Fill;
            btn_VK_N.FlatStyle = FlatStyle.Flat;
            btn_VK_N.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_N.Location = new Point(0x12b, 0x6f);
            btn_VK_N.Margin = new Padding(5);
            btn_VK_N.Name = "btn_VK_N";
            btn_VK_N.Size = new Size(0x58, 0x2b);
            btn_VK_N.TabIndex = 0x17;
            btn_VK_N.Text = "N";
            btn_VK_N.UseVisualStyleBackColor = true;
            btn_VK_N.Click += btn_VK_Click;
            btn_VK_M.Dock = DockStyle.Fill;
            btn_VK_M.FlatStyle = FlatStyle.Flat;
            btn_VK_M.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_M.Location = new Point(0xc9, 0x6f);
            btn_VK_M.Margin = new Padding(5);
            btn_VK_M.Name = "btn_VK_M";
            btn_VK_M.Size = new Size(0x58, 0x2b);
            btn_VK_M.TabIndex = 0x16;
            btn_VK_M.Text = "M";
            btn_VK_M.UseVisualStyleBackColor = true;
            btn_VK_M.Click += btn_VK_Click;
            btn_VK_L.Dock = DockStyle.Fill;
            btn_VK_L.FlatStyle = FlatStyle.Flat;
            btn_VK_L.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_L.Location = new Point(0x67, 0x6f);
            btn_VK_L.Margin = new Padding(5);
            btn_VK_L.Name = "btn_VK_L";
            btn_VK_L.Size = new Size(0x58, 0x2b);
            btn_VK_L.TabIndex = 0x15;
            btn_VK_L.Text = "L";
            btn_VK_L.UseVisualStyleBackColor = true;
            btn_VK_L.Click += btn_VK_Click;
            btn_VK_K.Dock = DockStyle.Fill;
            btn_VK_K.FlatStyle = FlatStyle.Flat;
            btn_VK_K.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_K.Location = new Point(5, 0x6f);
            btn_VK_K.Margin = new Padding(5);
            btn_VK_K.Name = "btn_VK_K";
            btn_VK_K.Size = new Size(0x58, 0x2b);
            btn_VK_K.TabIndex = 20;
            btn_VK_K.Text = "K";
            btn_VK_K.UseVisualStyleBackColor = true;
            btn_VK_K.Click += btn_VK_Click;
            btn_VK_J.Dock = DockStyle.Fill;
            btn_VK_J.FlatStyle = FlatStyle.Flat;
            btn_VK_J.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_J.Location = new Point(0x377, 0x3a);
            btn_VK_J.Margin = new Padding(5);
            btn_VK_J.Name = "btn_VK_J";
            btn_VK_J.Size = new Size(0x5c, 0x2b);
            btn_VK_J.TabIndex = 0x13;
            btn_VK_J.Text = "J";
            btn_VK_J.UseVisualStyleBackColor = true;
            btn_VK_J.Click += btn_VK_Click;
            btn_VK_I.Dock = DockStyle.Fill;
            btn_VK_I.FlatStyle = FlatStyle.Flat;
            btn_VK_I.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_I.Location = new Point(0x315, 0x3a);
            btn_VK_I.Margin = new Padding(5);
            btn_VK_I.Name = "btn_VK_I";
            btn_VK_I.Size = new Size(0x58, 0x2b);
            btn_VK_I.TabIndex = 0x12;
            btn_VK_I.Text = "I";
            btn_VK_I.UseVisualStyleBackColor = true;
            btn_VK_I.Click += btn_VK_Click;
            btn_VK_H.Dock = DockStyle.Fill;
            btn_VK_H.FlatStyle = FlatStyle.Flat;
            btn_VK_H.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_H.Location = new Point(0x2b3, 0x3a);
            btn_VK_H.Margin = new Padding(5);
            btn_VK_H.Name = "btn_VK_H";
            btn_VK_H.Size = new Size(0x58, 0x2b);
            btn_VK_H.TabIndex = 0x11;
            btn_VK_H.Text = "H";
            btn_VK_H.UseVisualStyleBackColor = true;
            btn_VK_H.Click += btn_VK_Click;
            btn_VK_G.Dock = DockStyle.Fill;
            btn_VK_G.FlatStyle = FlatStyle.Flat;
            btn_VK_G.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_G.Location = new Point(0x251, 0x3a);
            btn_VK_G.Margin = new Padding(5);
            btn_VK_G.Name = "btn_VK_G";
            btn_VK_G.Size = new Size(0x58, 0x2b);
            btn_VK_G.TabIndex = 0x10;
            btn_VK_G.Text = "G";
            btn_VK_G.UseVisualStyleBackColor = true;
            btn_VK_G.Click += btn_VK_Click;
            btn_VK_F.Dock = DockStyle.Fill;
            btn_VK_F.FlatStyle = FlatStyle.Flat;
            btn_VK_F.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_F.Location = new Point(0x1ef, 0x3a);
            btn_VK_F.Margin = new Padding(5);
            btn_VK_F.Name = "btn_VK_F";
            btn_VK_F.Size = new Size(0x58, 0x2b);
            btn_VK_F.TabIndex = 15;
            btn_VK_F.Text = "F";
            btn_VK_F.UseVisualStyleBackColor = true;
            btn_VK_F.Click += btn_VK_Click;
            btn_VK_E.Dock = DockStyle.Fill;
            btn_VK_E.FlatStyle = FlatStyle.Flat;
            btn_VK_E.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_E.Location = new Point(0x18d, 0x3a);
            btn_VK_E.Margin = new Padding(5);
            btn_VK_E.Name = "btn_VK_E";
            btn_VK_E.Size = new Size(0x58, 0x2b);
            btn_VK_E.TabIndex = 14;
            btn_VK_E.Text = "E";
            btn_VK_E.UseVisualStyleBackColor = true;
            btn_VK_E.Click += btn_VK_Click;
            btn_VK_D.Dock = DockStyle.Fill;
            btn_VK_D.FlatStyle = FlatStyle.Flat;
            btn_VK_D.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_D.Location = new Point(0x12b, 0x3a);
            btn_VK_D.Margin = new Padding(5);
            btn_VK_D.Name = "btn_VK_D";
            btn_VK_D.Size = new Size(0x58, 0x2b);
            btn_VK_D.TabIndex = 13;
            btn_VK_D.Text = "D";
            btn_VK_D.UseVisualStyleBackColor = true;
            btn_VK_D.Click += btn_VK_Click;
            btn_VK_C.Dock = DockStyle.Fill;
            btn_VK_C.FlatStyle = FlatStyle.Flat;
            btn_VK_C.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_C.Location = new Point(0xc9, 0x3a);
            btn_VK_C.Margin = new Padding(5);
            btn_VK_C.Name = "btn_VK_C";
            btn_VK_C.Size = new Size(0x58, 0x2b);
            btn_VK_C.TabIndex = 12;
            btn_VK_C.Text = "C";
            btn_VK_C.UseVisualStyleBackColor = true;
            btn_VK_C.Click += btn_VK_Click;
            btn_VK_B.Dock = DockStyle.Fill;
            btn_VK_B.FlatStyle = FlatStyle.Flat;
            btn_VK_B.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_B.Location = new Point(0x67, 0x3a);
            btn_VK_B.Margin = new Padding(5);
            btn_VK_B.Name = "btn_VK_B";
            btn_VK_B.Size = new Size(0x58, 0x2b);
            btn_VK_B.TabIndex = 11;
            btn_VK_B.Text = "B";
            btn_VK_B.UseVisualStyleBackColor = true;
            btn_VK_B.Click += btn_VK_Click;
            btn_VK_A.Dock = DockStyle.Fill;
            btn_VK_A.FlatStyle = FlatStyle.Flat;
            btn_VK_A.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_A.Location = new Point(5, 0x3a);
            btn_VK_A.Margin = new Padding(5);
            btn_VK_A.Name = "btn_VK_A";
            btn_VK_A.Size = new Size(0x58, 0x2b);
            btn_VK_A.TabIndex = 10;
            btn_VK_A.Text = "A";
            btn_VK_A.UseVisualStyleBackColor = true;
            btn_VK_A.Click += btn_VK_Click;
            btn_VK_0.Dock = DockStyle.Fill;
            btn_VK_0.FlatStyle = FlatStyle.Flat;
            btn_VK_0.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_0.Location = new Point(0x377, 5);
            btn_VK_0.Margin = new Padding(5);
            btn_VK_0.Name = "btn_VK_0";
            btn_VK_0.Size = new Size(0x5c, 0x2b);
            btn_VK_0.TabIndex = 9;
            btn_VK_0.Text = "0";
            btn_VK_0.UseVisualStyleBackColor = true;
            btn_VK_0.Click += btn_VK_Click;
            btn_VK_9.Dock = DockStyle.Fill;
            btn_VK_9.FlatStyle = FlatStyle.Flat;
            btn_VK_9.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_9.Location = new Point(0x315, 5);
            btn_VK_9.Margin = new Padding(5);
            btn_VK_9.Name = "btn_VK_9";
            btn_VK_9.Size = new Size(0x58, 0x2b);
            btn_VK_9.TabIndex = 8;
            btn_VK_9.Text = "9";
            btn_VK_9.UseVisualStyleBackColor = true;
            btn_VK_9.Click += btn_VK_Click;
            btn_VK_8.Dock = DockStyle.Fill;
            btn_VK_8.FlatStyle = FlatStyle.Flat;
            btn_VK_8.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_8.Location = new Point(0x2b3, 5);
            btn_VK_8.Margin = new Padding(5);
            btn_VK_8.Name = "btn_VK_8";
            btn_VK_8.Size = new Size(0x58, 0x2b);
            btn_VK_8.TabIndex = 7;
            btn_VK_8.Text = "8";
            btn_VK_8.UseVisualStyleBackColor = true;
            btn_VK_8.Click += btn_VK_Click;
            btn_VK_7.Dock = DockStyle.Fill;
            btn_VK_7.FlatStyle = FlatStyle.Flat;
            btn_VK_7.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_7.Location = new Point(0x251, 5);
            btn_VK_7.Margin = new Padding(5);
            btn_VK_7.Name = "btn_VK_7";
            btn_VK_7.Size = new Size(0x58, 0x2b);
            btn_VK_7.TabIndex = 6;
            btn_VK_7.Text = "7";
            btn_VK_7.UseVisualStyleBackColor = true;
            btn_VK_7.Click += btn_VK_Click;
            btn_VK_6.Dock = DockStyle.Fill;
            btn_VK_6.FlatStyle = FlatStyle.Flat;
            btn_VK_6.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_6.Location = new Point(0x1ef, 5);
            btn_VK_6.Margin = new Padding(5);
            btn_VK_6.Name = "btn_VK_6";
            btn_VK_6.Size = new Size(0x58, 0x2b);
            btn_VK_6.TabIndex = 5;
            btn_VK_6.Text = "6";
            btn_VK_6.UseVisualStyleBackColor = true;
            btn_VK_6.Click += btn_VK_Click;
            btn_VK_5.Dock = DockStyle.Fill;
            btn_VK_5.FlatStyle = FlatStyle.Flat;
            btn_VK_5.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_5.Location = new Point(0x18d, 5);
            btn_VK_5.Margin = new Padding(5);
            btn_VK_5.Name = "btn_VK_5";
            btn_VK_5.Size = new Size(0x58, 0x2b);
            btn_VK_5.TabIndex = 4;
            btn_VK_5.Text = "5";
            btn_VK_5.UseVisualStyleBackColor = true;
            btn_VK_5.Click += btn_VK_Click;
            btn_VK_4.Dock = DockStyle.Fill;
            btn_VK_4.FlatStyle = FlatStyle.Flat;
            btn_VK_4.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_4.Location = new Point(0x12b, 5);
            btn_VK_4.Margin = new Padding(5);
            btn_VK_4.Name = "btn_VK_4";
            btn_VK_4.Size = new Size(0x58, 0x2b);
            btn_VK_4.TabIndex = 3;
            btn_VK_4.Text = "4";
            btn_VK_4.UseVisualStyleBackColor = true;
            btn_VK_4.Click += btn_VK_Click;
            btn_VK_3.Dock = DockStyle.Fill;
            btn_VK_3.FlatStyle = FlatStyle.Flat;
            btn_VK_3.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_3.Location = new Point(0xc9, 5);
            btn_VK_3.Margin = new Padding(5);
            btn_VK_3.Name = "btn_VK_3";
            btn_VK_3.Size = new Size(0x58, 0x2b);
            btn_VK_3.TabIndex = 2;
            btn_VK_3.Text = "3";
            btn_VK_3.UseVisualStyleBackColor = true;
            btn_VK_3.Click += btn_VK_Click;
            btn_VK_2.Dock = DockStyle.Fill;
            btn_VK_2.FlatStyle = FlatStyle.Flat;
            btn_VK_2.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_2.Location = new Point(0x67, 5);
            btn_VK_2.Margin = new Padding(5);
            btn_VK_2.Name = "btn_VK_2";
            btn_VK_2.Size = new Size(0x58, 0x2b);
            btn_VK_2.TabIndex = 1;
            btn_VK_2.Text = "2";
            btn_VK_2.UseVisualStyleBackColor = true;
            btn_VK_2.Click += btn_VK_Click;
            btn_VK_1.Dock = DockStyle.Fill;
            btn_VK_1.FlatStyle = FlatStyle.Flat;
            btn_VK_1.Font = new Font("Segoe UI", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xcc);
            btn_VK_1.Location = new Point(5, 5);
            btn_VK_1.Margin = new Padding(5);
            btn_VK_1.Name = "btn_VK_1";
            btn_VK_1.Size = new Size(0x58, 0x2b);
            btn_VK_1.TabIndex = 0;
            btn_VK_1.Text = "1";
            btn_VK_1.UseVisualStyleBackColor = true;
            btn_VK_1.Click += btn_VK_Click;
            Apartment.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            Apartment.DataPropertyName = "Apartment";
            style3.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xcc);
            Apartment.DefaultCellStyle = style3;
            Apartment.HeaderText = "Apartment";
            Apartment.Name = "Apartment";
            Apartment.ReadOnly = true;
            TenantName.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            TenantName.DataPropertyName = "Name";
            style4.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xcc);
            TenantName.DefaultCellStyle = style4;
            TenantName.HeaderText = "Tenant name";
            TenantName.MinimumWidth = 600;
            TenantName.Name = "TenantName";
            TenantName.ReadOnly = true;
            TenantName.Resizable = DataGridViewTriState.False;
            TenantName.SortMode = DataGridViewColumnSortMode.NotSortable;
            TenantName.Width = 600;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(0xcd, 0xcd, 0xcd);
            base.CancelButton = btnCancel;
            base.ClientSize = new Size(0x428, 0x323);
            base.Controls.Add(pnlKeyboardContainer);
            base.Controls.Add(pnlFilter);
            base.Controls.Add(pnlDataGrid);
            base.Controls.Add(pnlButtons);
            base.FormBorderStyle = FormBorderStyle.None;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "IdentifyTenantForm2";
            Text = "IdentifyTenantForm2";
            base.WindowState = FormWindowState.Maximized;
            base.FormClosed += IdentifyTenantForm2_FormClosed;
            base.Load += IdentifyTenantForm2_Load;
            pnlButtons.ResumeLayout(false);
            ((ISupportInitialize) dgvTenants).EndInit();
            pnlDataGrid.ResumeLayout(false);
            pnlFilter.ResumeLayout(false);
            pnlFilter.PerformLayout();
            pnlKeyboardContainer.ResumeLayout(false);
            tblButtonsContainer.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        private void SetFocusToInput()
        {
            txtFilter.Select();
            txtFilter.Focus();
        }

        private DataTable ToDataTable<T>(IList<T> data)
        {
            PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(typeof (T));
            var table = new DataTable();
            foreach (PropertyDescriptor descriptor in properties)
            {
                table.Columns.Add(descriptor.Name,
                                  Nullable.GetUnderlyingType(descriptor.PropertyType) ?? descriptor.PropertyType);
            }
            foreach (T local in data)
            {
                DataRow row = table.NewRow();
                foreach (PropertyDescriptor descriptor in properties)
                {
                    row[descriptor.Name] = descriptor.GetValue(local) ?? DBNull.Value;
                }
                table.Rows.Add(row);
            }
            return table;
        }

        private void txtFilter_TextChanged(object sender, EventArgs e)
        {
            if (dgvTenants.DataSource == null)
            {
                dgvTenants.DataSource = tableSource;
            }
            ((DataTable) dgvTenants.DataSource).DefaultView.RowFilter = "Name LIKE '%" + txtFilter.Text +
                                                                        "%' OR Apartment LIKE '%" +
                                                                        txtFilter.Text + "%'";
        }
    }
}